spring:
  datasource:
    url: jdbc:mysql://localhost:23306/mybatis
    username: root
    password: nirvana

mybatis-plus:
  typeAliasesPackage: com.iblotus.javamybatisdemo.domain
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
